### ISSUE TITLE
Issue with [Fate Auto Sync]

### ISSUE THREAD

**Issue by iRobsie** [Aida-Enna/XIVPlugins#10]
The plugin no longer works for me as of recent. The commands do not work, and they throw errors in the log when I try to process them. Provided are the errors.

```
Info
System.NullReferenceException: Object reference not set to an instance of an object.
   at FATEAutoSync.Plugin.ToggleAutoFate(String command, String args) in D:\Programming\XIVPlugins\FATEAutoSync\Plugin.cs:line 149
   at Dalamud.Game.Command.CommandManager.DispatchCommand(String command, String argument, CommandInfo info) in C:\goatsoft\companysecrets\dalamud\Game\Command\CommandManager.cs:line 117
Context
Error while dispatching command "/autofate" (Argument: "")
```

**Comment by Aida-Enna** [comment]
Oh, huh. I'll take a look and fix it, thanks!

**Comment by Aida-Enna** [comment]
Fixed in https://github.com/Aida-Enna/XIVPlugins/commit/0860dea9c9bb82d2914071859b29cd8ceffe123b, thanks again! 👍
